name: Latest blog post workflow
on:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in nmfc posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.notmyfirstcodeo.com/rss.xml,https://medium.com/feed/@sf-adams"
          feed_names: "Blog, Medium"
          max_post_count: 5
          #tag_post_pre_newline: true
          #template: "$newline - [$feedName: $title]($url)"
